### ISSUE TITLE
It's possible to pass connection string which is undefined

### ISSUE THREAD

**Issue by Pabliomen** [pkosiec/mongo-seeding#147] opened 2021-02-15 09:12 UTC
Hi, this is my first time putting up a issue but i found something that really took me some time to debug.
the issue i was having is that my code runned but didn't seed the database. After further inspection my connection url was undefined because i was using dot-env  to load in the connection string (which i didn't require in the seed file). after requiring the dot-env everything worked. but i was thinking.  Can we get error when the conection string you give is undefined?

**Comment by pkosiec** [comment] 2021-03-06 09:36
Hi @Pabliomen,
Sorry for long delay. By default, the provided configuration is merged with the one you provided, so in case of `undefined` the default values are used. Here's even a test for that:
https://github.com/pkosiec/mongo-seeding/blob/master/core/test/unit/config.ts#L41

Did you encounter this problem with core or CLI?

Cheers!

**Comment by pkosiec** [comment] 2021-03-21 14:23
I'm closing this issue for now, as currently I cannot reproduce it. Please write down some more details and then I will be able to reopen it. Thanks!

**Closed by pkosiec** 2021-03-21 14:23 UTC
Labels: needs more info
