### ISSUE TITLE
mongodb version v3 to v4

### ISSUE THREAD

**Issue by GW00D** [pkosiec/mongo-seeding#202] opened 2022-12-15 20:53 UTC
Would appreciate if the mongodb version was upgraded to v4 as it's causing issues in my project

**Comment by pkosiec** [comment] 2022-12-15 21:21
Hi, closing this as it is a duplicate of https://github.com/pkosiec/mongo-seeding/issues/187. Will try to implement soon 🙂 If you'd like to help, please let me know.

**Closed by pkosiec** 2022-12-15 21:21 UTC
Labels: duplicate, area/core, dependencies
